### ISSUE TITLE
unable to retrive Dataset with converted units

### ISSUE THREAD

**Issue by raybellwaves** [xarray-contrib/pint-xarray#109]
This is a strange and i'm not sure if I can make a MCVE. I'll try later.

The tutorial equations works fine so must be something else i'm doing
```
VAR = "air"
OUNIT = "degC"

ds = xr.tutorial.open_dataset("air_temperature")
ds["lat"].attrs["units"] = "degree"
ds["lon"].attrs["units"] = "degree"

ds = ds.pint.quantify({VAR: ds[VAR].attrs["units"]})
ds = ds.pint.to({VAR: OUNIT})
ds = ds.pint.dequantify(format="~P")

ds[VAR].isel(time=0).plot()

ds.to_netcdf("/tmp/tmp.nc")
ds = xr.open_dataset("/tmp/tmp.nc")

ds[VAR].isel(time=0).plot()
```

I'm trying to save a Dataset where I can converted the units.

I'm unable to see the converted units after loading straight after saving.

The code is something like the example above but with a few extra ETL steps.

<img width="477" alt="Screen Shot 2021-05-31 at 11 56 28 PM" src="https://user-images.githubusercontent.com/17162724/120264451-d40f6500-c26b-11eb-8a04-476a5e1652ed.png">

**Comment by raybellwaves** [comment]
Closing as seems to be ok with pickle. It's a temp store anyway.

```
pickle.dump(ds, open("/tmp/ds.pkl", "wb"), protocol=-1)
ds = pickle.load(open("/tmp/ds.pkl", "rb"))
```

**Comment by raybellwaves** [comment]
https://github.com/pydata/xarray/discussions/5407#discussioncomment-812278

**Comment by keewis** [comment]
does that mean your code works if you clear `.encoding` before saving?

**Comment by raybellwaves** [comment]
> does that mean your code works if you clear `.encoding` before saving?

Correct that was my work around
