### ISSUE TITLE
units = "none"?

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/pint-xarray#118]
I have a dataset with some variables with `units: "none"`. Can we ignore this in pint-xarray or is that not clean enough?

**Comment by keewis** [comment]
not sure. We currently have `None` as a way to mark "non-quantities", but I guess we could add `1` and maybe `"none"` and `"1"`, too. The only issue would be whether `"none"` conflicts with an actual unit (probably not, though).

**Comment by keewis** [comment]
apparently we don't support anything like that, yet: while `None` is used internally to mark "non-quantities", we also use `None` in the function signatures (especially `_decide_units`). The result is that overrides are silently ignored, which is truly unfortunate.
