### ISSUE TITLE
publish to conda-forge

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/pint-xarray#38]
Now that `pint-xarray` is on PyPI, we should also publish it to `conda-forge`. Before I do that: @xarray-contrib/pint-xarray-devs, does anyone want to help me maintain that package?

**Comment by jthielen** [comment]
I'd be glad to help in maintaining that package the longer-term going forward (though my ability to help will be a bit hampered in the coming month still)...hopefully that's okay!

**Comment by keewis** [comment]
no worries, there shouldn't be much to do in the next few months. I just would like to avoid being the only maintainer. Same also for RTD, I guess?

**Comment by jthielen** [comment]
> Same also for RTD, I guess?

Sounds good! Admittedly, I haven't worked with RTD before, so I may need to do a little bit more reading up on that.

**Comment by keewis** [comment]
well, there's not much to read up on, the only thing you can do with the web interface you can't do with the configuration file is to activate / deactivate tags and branches, and rerunning their builds. There's more, of course, but that's something that can be figured out once it's needed.

The only issue is that you would have to sign up (it is possible to sign up using Github, though).

**Comment by keewis** [comment]
`pint-xarray` is now available on `conda-forge`
